module.exports = function () {
  return [
    {
      series: "Angela",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Dec 1994",
      release_year: 1994,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.25,
    },
    {
      series: "Angela",
      issue: "2A",
      issue_nr: 2,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jan 1995",
      release_year: 1995,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.25,
    },
    {
      series: "Angela",
      issue: "3",
      issue_nr: 3,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Feb 1995",
      release_year: 1995,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.25,
    },
    {
      series: "The Art of Homage Studios",
      issue: "1",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Dec 1993",
      release_year: 1993,
      genre: "",
      format: "Squarebound",
      pages: 48,
      price: 4.95,
    },
    {
      series: "Cable and The New Mutants",
      issue: "TP",
      issue_nr: null,
      full_title: "New Mutants, Vol. 1 #87-94",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "TP",
      publisher: "Marvel Comics",
      release_date: "Jun 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Trade Paperback",
      pages: 176,
      price: 15.95,
    },
    {
      series: "The Creech",
      issue: "1A",
      issue_nr: 1,
      full_title: "A Vision Of Death",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1997",
      release_year: 1997,
      genre: "Adventure",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "The Creech",
      issue: "2",
      issue_nr: 2,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Nov 1997",
      release_year: 1997,
      genre: "Adventure",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "The Creech",
      issue: "3",
      issue_nr: 3,
      full_title: "The Resurrection",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Dec 1997",
      release_year: 1997,
      genre: "",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "The Creech: Out For Blood",
      issue: 1,
      issue_nr: 1,
      full_title: "Out For Blood",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Jun 2001",
      release_year: 2001,
      genre: "",
      format: "Comic",
      pages: 48,
      price: 4.95,
    },
    {
      series: "The Creech: Out For Blood",
      issue: 2,
      issue_nr: 2,
      full_title: "Wake The Dead",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Sep 2001",
      release_year: 2001,
      genre: "Action",
      format: "Comic",
      pages: 48,
      price: 4.95,
    },
    {
      series: "Cyberforce, Vol. 1",
      issue: "0A",
      issue_nr: 0,
      full_title: "Mindgames",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Sep 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 36,
      price: 1.95,
    },
    {
      series: "Cyberforce, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "The Tin Men Of War, Part 1",
      subtitle: "",
      story_arc: "The Tin Men Of War",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Cyberforce, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "The Tin Men Of War, Part 2",
      subtitle: "",
      story_arc: "The Tin Men Of War",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Cyberforce, Vol. 1",
      issue: "3A",
      issue_nr: 3,
      full_title: "The Tin Men Of War, Part 3",
      subtitle: "",
      story_arc: "The Tin Men Of War",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Cyberforce, Vol. 1",
      issue: "4A",
      issue_nr: 4,
      full_title: "The Tin Men Of War, Part 4",
      subtitle: "",
      story_arc: "The Tin Men Of War",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Cyberrad, Vol. 2",
      issue: "1B",
      issue_nr: 1,
      full_title: "Just Say No",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Continuity Comics",
      release_date: "Nov 1992",
      release_year: 1992,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.95,
    },
    {
      series: "Darker Image",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Deathblow, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "Confessions",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Apr 1993",
      release_year: 1993,
      genre: "Adventure | Super-Heroes | War",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Deathblow, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Aug 1993",
      release_year: 1993,
      genre: "Action | Adventure | Science Fiction | Super-Heroes | War",
      format: "Comic",
      pages: 36,
      price: 1.75,
    },
    {
      series: "Divine Right",
      issue: "2A",
      issue_nr: 2,
      full_title: "Disco Inferno",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1997",
      release_year: 1997,
      genre: "Fantasy",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Divine Right",
      issue: "3A",
      issue_nr: 3,
      full_title: "Enemies Of The State",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Nov 1997",
      release_year: 1997,
      genre: "",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "DV8 vs. BlackOps",
      issue: "1",
      issue_nr: 1,
      full_title: "The Techtromis Design, Part 1",
      subtitle: "",
      story_arc: "The Techtromis Design",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Oct 1997",
      release_year: 1997,
      genre: "Action | Adventure | Super-Heroes | War",
      format: "Comic",
      pages: 40,
      price: 2.5,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "1A",
      issue_nr: 1,
      full_title: "Renaissance",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 04, 1996",
      release_year: 1996,
      genre: "",
      format: "Comic",
      pages: 56,
      price: 2.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "2A",
      issue_nr: 2,
      full_title: "Repercussions",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Dec 1996",
      release_year: 1996,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 40,
      price: 1.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "3A",
      issue_nr: 3,
      full_title: "Revelations",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Nov 06, 1996",
      release_year: 1996,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 40,
      price: 1.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "5A",
      issue_nr: 5,
      full_title: "Auld Acquaintance",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 1997",
      release_year: 1997,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 40,
      price: 1.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "6A",
      issue_nr: 6,
      full_title: "Industrial Revolution - Retribution",
      subtitle: "Industrial Revolution: Prologue for Heroes Reborn",
      story_arc: "",
      crossover: "Industrial Revolution",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 1997",
      release_year: 1997,
      genre: "Action | Adventure | Science Fiction",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "7A",
      issue_nr: 7,
      full_title: "Into the Negative Zone!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "May 1997",
      release_year: 1997,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "8A",
      issue_nr: 8,
      full_title: "The Ties That Bind",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jun 1997",
      release_year: 1997,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Fantastic Four, Vol. 2",
      issue: "9A",
      issue_nr: 9,
      full_title: "Legacy",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jul 1997",
      release_year: 1997,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Gen 13, Vol. 1 (1994)",
      issue: "TP",
      issue_nr: null,
      full_title: "Gen 13",
      subtitle: "Collected Edition",
      story_arc: "",
      crossover: "",
      variant: "TP",
      publisher: "Image Comics",
      release_date: "Dec 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Trade Paperback",
      pages: 144,
      price: 12.95,
    },
    {
      series: "Gen 13, Vol. 1 (1994)",
      issue: "0A",
      issue_nr: 0,
      full_title: "Coming Home / Desert Bloom / The Big Deal / Things Change",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Sep 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Gen 13, Vol. 1 (1994)",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Feb 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Gen 13, Vol. 1 (1994)",
      issue: "3",
      issue_nr: 3,
      full_title: "Payback",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Jul 1995",
      release_year: 1995,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Ghost Rider, Vol. 2",
      issue: "26A",
      issue_nr: 26,
      full_title: "Blood Feud!, Part 2",
      subtitle: "",
      story_arc: "Blood Feud!",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 14, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Ghost Rider, Vol. 2",
      issue: "27A",
      issue_nr: 27,
      full_title: "Part 4: Vengeance. Pure and Simple.",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "May 12, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Image Plus",
      issue: "1",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Reference",
      format: "Comic",
      pages: 32,
      price: 2.25,
    },
    {
      series: "Image Zero",
      issue: "0",
      issue_nr: 0,
      full_title: "Prey",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Oct 12, 1993",
      release_year: 1993,
      genre: "Adventure",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Images of Shadowhawk",
      issue: "1",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Sep 1993",
      release_year: 1993,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "The Incredible Hulk, Vol. 1",
      issue: "391A",
      issue_nr: 391,
      full_title: "War & Pieces, Part 2: X-Calation",
      subtitle: "",
      story_arc: "War & Pieces",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jan 21, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "The Incredible Hulk, Vol. 1",
      issue: "391B",
      issue_nr: 391,
      full_title: "War & Pieces, Part 2: X-Calation",
      subtitle: "",
      story_arc: "War & Pieces",
      crossover: "",
      variant: "B",
      publisher: "Marvel Comics",
      release_date: "Jan 21, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "The Incredible Hulk, Vol. 1",
      issue: "392A",
      issue_nr: 392,
      full_title: "War & Pieces, Part 3: Fortunes of War",
      subtitle: "",
      story_arc: "War & Pieces",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 18, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "Iron Man, Vol. 2",
      issue: "1A",
      issue_nr: 1,
      full_title: "Heart of the Matter",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 18, 1996",
      release_year: 1996,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 56,
      price: 2.95,
    },
    {
      series: "Jim Henson's Power of The Dark Crystal",
      issue: "1B",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Boom! Studios",
      release_date: "Feb 22, 2017",
      release_year: 2017,
      genre: "Fantasy",
      format: "Comic",
      pages: 32,
      price: 3.99,
    },
    {
      series: "Justice League Europe / International",
      issue: "15A",
      issue_nr: 15,
      full_title: "The Extremist Vector, Part 1: Kings of the Dust",
      subtitle: "",
      story_arc: "The Extremist Vector",
      crossover: "",
      variant: "A",
      publisher: "DC Comics",
      release_date: "Jun 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "Justice League Europe / International",
      issue: "16A",
      issue_nr: 16,
      full_title: "The Extremist Vector, Part 2: Conquest",
      subtitle: "",
      story_arc: "The Extremist Vector",
      crossover: "",
      variant: "A",
      publisher: "DC Comics",
      release_date: "Jul 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "Justice League Europe / International",
      issue: "17A",
      issue_nr: 17,
      full_title: "The Extremist Vector, Part 3: On The Brink!",
      subtitle: "",
      story_arc: "The Extremist Vector",
      crossover: "",
      variant: "A",
      publisher: "DC Comics",
      release_date: "Aug 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "Justice League Europe / International",
      issue: "18A",
      issue_nr: 18,
      full_title: "The Extremist Vector, Part 4: The Happy Place",
      subtitle: "",
      story_arc: "The Extremist Vector",
      crossover: "",
      variant: "A",
      publisher: "DC Comics",
      release_date: "Sep 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "Justice League Europe / International",
      issue: "19A",
      issue_nr: 19,
      full_title: "The Extremist Vector, Part 5: Pushing The Buttons",
      subtitle: "",
      story_arc: "The Extremist Vector",
      crossover: "",
      variant: "A",
      publisher: "DC Comics",
      release_date: "Oct 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "Marvel Swimsuit Special",
      issue: "1",
      issue_nr: 1,
      full_title: "Take A Wakanda Wild Side",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Marvel Comics",
      release_date: "Jun 23, 1992",
      release_year: 1992,
      genre: "Art / Pin-up | Hobby",
      format: "Magazine",
      pages: 48,
      price: 3.95,
    },
    {
      series: "The Maxx",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "The Maxx",
      issue: "2A",
      issue_nr: 2,
      full_title: "Stained Teeth, Deadly Teeth",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Apr 1993",
      release_year: 1993,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "The Maxx",
      issue: "3A",
      issue_nr: 3,
      full_title: "Jungle Flowers Grown in Blood",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "The Maxx",
      issue: "4A",
      issue_nr: 4,
      full_title: "Maxx!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Apr 1993",
      release_year: 1993,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "New Mutants, Vol. 1",
      issue: "87A",
      issue_nr: 87,
      full_title: "A Show Of Power!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jan 09, 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "New Mutants, Vol. 1",
      issue: "100A",
      issue_nr: 100,
      full_title: "The End Of The Beginning",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 13, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 52,
      price: null,
    },
    {
      series: "Pitt",
      issue: "1A",
      issue_nr: 1,
      full_title: "Fight & Flight!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jan 1993",
      release_year: 1993,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Pitt",
      issue: "2A",
      issue_nr: 2,
      full_title: "Dead or Alive",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Pitt",
      issue: "3A",
      issue_nr: 3,
      full_title: "The Killing Gate / Crash Of Souls",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Feb 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Savage Dragon vs. Savage Megaton Man",
      issue: "1A",
      issue_nr: 1,
      full_title: "Savage Brawl",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Adventure",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "The Savage Dragon [SP]",
      issue: "1",
      issue_nr: 1,
      full_title: "Un dÃ­a duro",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Jun 1993",
      release_year: 1993,
      genre: "",
      format: "Comic",
      pages: 0,
      price: null,
    },
    {
      series: "The Savage Dragon [SP]",
      issue: "2",
      issue_nr: 2,
      full_title: "I love NY",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre: "",
      format: "Comic",
      pages: 0,
      price: null,
    },
    {
      series: "The Savage Dragon [SP]",
      issue: "3",
      issue_nr: 3,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Aug 1993",
      release_year: 1993,
      genre: "",
      format: "Comic",
      pages: 0,
      price: null,
    },
    {
      series: "The Savage Dragon [SP]",
      issue: "4",
      issue_nr: 4,
      full_title: "Nuevos reclutas",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Sep 1993",
      release_year: 1993,
      genre: "",
      format: "Comic",
      pages: 0,
      price: null,
    },
    {
      series: "Savage Dragon, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "Baptism Of Fire",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1992",
      release_year: 1992,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Savage Dragon, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "Born Again Patriot",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1992",
      release_year: 1992,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Savage Dragon, Vol. 1",
      issue: "3A",
      issue_nr: 3,
      full_title: "Rock This Town",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Dec 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Shadowhawk, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "A Nightmare Walking",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Aug 1992",
      release_year: 1992,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Shadowhawk, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "A Good Night For Arson",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1992",
      release_year: 1992,
      genre: "Action | Adventure",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Shadowhawk, Vol. 1",
      issue: "3A",
      issue_nr: 3,
      full_title: "Liquid Fire",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Dec 1992",
      release_year: 1992,
      genre: "Adventure",
      format: "Comic",
      pages: 28,
      price: 2.5,
    },
    {
      series: "Shadowhawk, Vol. 1",
      issue: "4A",
      issue_nr: 4,
      full_title: "Enter: The Dragon",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Action | Adventure",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Shadowhawk, Vol. 2",
      issue: "1",
      issue_nr: 1,
      full_title: "The Shadow of the Hawk",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 3.5,
    },
    {
      series: "Shadowhawk, Vol. 2",
      issue: "2A",
      issue_nr: 2,
      full_title: "The Secret Revealed",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre: "Adventure",
      format: "Comic",
      pages: 36,
      price: 1.95,
    },
    {
      series: "Shadowhawk, Vol. 2",
      issue: "3",
      issue_nr: 3,
      full_title: "Like Lambs to the...",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Aug 1993",
      release_year: 1993,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.95,
    },
    {
      series: "Spawn",
      issue: "1A",
      issue_nr: 1,
      full_title: "Questions, Part 1",
      subtitle: "",
      story_arc: "Questions",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "May 1992",
      release_year: 1992,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "2A",
      issue_nr: 2,
      full_title: "Questions, Part 2",
      subtitle: "",
      story_arc: "Questions",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jun 1992",
      release_year: 1992,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "3A",
      issue_nr: 3,
      full_title: "Questions, Part 3",
      subtitle: "",
      story_arc: "Questions",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1992",
      release_year: 1992,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "4A",
      issue_nr: 4,
      full_title: "Questions, Part 4",
      subtitle: "",
      story_arc: "Questions",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Sep 1992",
      release_year: 1992,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Spawn",
      issue: "5A",
      issue_nr: 5,
      full_title: "Justice",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1992",
      release_year: 1992,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "6A",
      issue_nr: 6,
      full_title: "Payback, Part 1",
      subtitle: "",
      story_arc: "Payback",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Nov 1992",
      release_year: 1992,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "7A",
      issue_nr: 7,
      full_title: "Payback, Part 2",
      subtitle: "",
      story_arc: "Payback",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jan 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Spawn",
      issue: "8A",
      issue_nr: 8,
      full_title: "In Heaven (Everything Is Fine)",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Feb 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 36,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "9A",
      issue_nr: 9,
      full_title: "Angela",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 36,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "10A",
      issue_nr: 10,
      full_title: "Crossing Over",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "11A",
      issue_nr: 11,
      full_title: "Home Story",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jun 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "12A",
      issue_nr: 12,
      full_title: "Flashback, Part 1",
      subtitle: "",
      story_arc: "Flashback",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "13A",
      issue_nr: 13,
      full_title: "Flashback, Part 2",
      subtitle: "",
      story_arc: "Flashback",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Aug 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "15A",
      issue_nr: 15,
      full_title: "Myths, Part 2",
      subtitle: "",
      story_arc: "Myths",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Nov 1993",
      release_year: 1993,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "59A",
      issue_nr: 59,
      full_title: "Vanished",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1997",
      release_year: 1997,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "60A",
      issue_nr: 60,
      full_title: "Dwarfed",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Apr 1997",
      release_year: 1997,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "61A",
      issue_nr: 61,
      full_title: "Sanctuary",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "May 1997",
      release_year: 1997,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "68A",
      issue_nr: 68,
      full_title: "Intersection",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jan 1998",
      release_year: 1998,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "69A",
      issue_nr: 69,
      full_title: "Freaky",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jan 1998",
      release_year: 1998,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "77A",
      issue_nr: 77,
      full_title: "Relics",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Oct 1998",
      release_year: 1998,
      genre: "Action | Adventure | Horror | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spawn",
      issue: "78A",
      issue_nr: 78,
      full_title: "Bloodstains",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Nov 1999",
      release_year: 1999,
      genre:
        "Action | Adventure | Crime | Fantasy | Horror | Science Fiction | Super-Heroes | Thriller",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "6A",
      issue_nr: 6,
      full_title: "Masques, Part 1",
      subtitle: "",
      story_arc: "Masques",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Nov 20, 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "7A",
      issue_nr: 7,
      full_title: "Masques, Part 2",
      subtitle: "",
      story_arc: "Masques",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Dec 18, 1990",
      release_year: 1990,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "8A",
      issue_nr: 8,
      full_title: "Perceptions, Part 1",
      subtitle: "",
      story_arc: "Perceptions",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jan 15, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "9A",
      issue_nr: 9,
      full_title: "Perceptions, Part 2",
      subtitle: "",
      story_arc: "Perceptions",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 19, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "10A",
      issue_nr: 10,
      full_title: "Perceptions, Part 3",
      subtitle: "",
      story_arc: "Perceptions",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 19, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "11A",
      issue_nr: 11,
      full_title: "Perceptions, Part 4",
      subtitle: "",
      story_arc: "Perceptions",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 16, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "12A",
      issue_nr: 12,
      full_title: "Perceptions, Perceptions, Part 5 of 5",
      subtitle: "",
      story_arc: "Perceptions",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "May 21, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "13A",
      issue_nr: 13,
      full_title: "Sub-City, Part One",
      subtitle: "",
      story_arc: "Sub-City",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jun 18, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "14A",
      issue_nr: 14,
      full_title: "Sub-City, Part Two",
      subtitle: "",
      story_arc: "Sub-City",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jul 16, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "15A",
      issue_nr: 15,
      full_title: "The Mutant Factor!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Oct 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "16A",
      issue_nr: 16,
      full_title: "Sabotage - Part 1",
      subtitle: "",
      story_arc: "",
      crossover: "Sabotage",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 17, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "18A",
      issue_nr: 18,
      full_title: "Revenge of the Sinister Six, Part One: Revenge",
      subtitle: "",
      story_arc: "Revenge of the Sinister Six",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Nov 19, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "19A",
      issue_nr: 19,
      full_title:
        "Revenge of the Sinister Six, Part Two: Slugfest / Diabolique Part 1",
      subtitle: "",
      story_arc: "Revenge of the Sinister Six",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "20A",
      issue_nr: 20,
      full_title:
        "Revenge of the Sinister Six, Part Three: Showdown / Diabolique Part 2",
      subtitle: "",
      story_arc: "Revenge of the Sinister Six",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "21A",
      issue_nr: 21,
      full_title: "Revenge of the Sinister Six, Part Four: Dealing Arms",
      subtitle: "",
      story_arc: "Revenge of the Sinister Six",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "22A",
      issue_nr: 22,
      full_title: "Revenge of the Sinister Six, Part Five: The Sixth Member",
      subtitle: "",
      story_arc: "Revenge of the Sinister Six",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 17, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "23A",
      issue_nr: 23,
      full_title: "Revenge of the Sinister Six, Part Six: Confrontation",
      subtitle: "",
      story_arc: "Revenge of the Sinister Six",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 21, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.75,
    },
    {
      series: "Spider-Man, Vol. 1",
      issue: "26A",
      issue_nr: 26,
      full_title: "With Great Responsibility -- !",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 48,
      price: 3.5,
    },
    {
      series: "Spider-Man vs. Venom",
      issue: "A",
      issue_nr: null,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "1990",
      release_year: 1990,
      genre: "Action | Super-Heroes",
      format: "Softcover",
      pages: 112,
      price: 12.95,
    },
    {
      series: "Spider-Man: Torment",
      issue: "TP-A",
      issue_nr: null,
      full_title: "Torment",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "TP-A",
      publisher: "Marvel Comics",
      release_date: "Jan 1992",
      release_year: 1992,
      genre: "Action | Super-Heroes",
      format: "Trade Paperback",
      pages: 0,
      price: 12.95,
    },
    {
      series: "Star Wars: Episode 1 - Phantom Menace",
      issue: "1B",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Dark Horse Comics",
      release_date: "May 1999",
      release_year: 1999,
      genre: "Action | Adventure | Science Fiction",
      format: "Comic",
      pages: 32,
      price: 2.95,
    },
    {
      series: "Star Wars: Episode 1 - Phantom Menace",
      issue: "2B",
      issue_nr: 2,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Dark Horse Comics",
      release_date: "May 1999",
      release_year: 1999,
      genre: "Action | Adventure | Science Fiction",
      format: "Comic",
      pages: 32,
      price: 2.95,
    },
    {
      series: "Star Wars: Episode 1 - Phantom Menace",
      issue: "3B",
      issue_nr: 3,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Dark Horse Comics",
      release_date: "May 1999",
      release_year: 1999,
      genre: "Action | Adventure | Science Fiction",
      format: "Comic",
      pages: 32,
      price: 2.95,
    },
    {
      series: "Star Wars: Episode 1 - Phantom Menace",
      issue: "4B",
      issue_nr: 4,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Dark Horse Comics",
      release_date: "May 1999",
      release_year: 1999,
      genre: "Action | Adventure | Science Fiction",
      format: "Comic",
      pages: 32,
      price: 2.95,
    },
    {
      series: "Stormwatch, Vol. 1",
      issue: "0",
      issue_nr: 0,
      full_title: "StormWatch",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Aug 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Stormwatch, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Stormwatch, Vol. 1",
      issue: "2",
      issue_nr: 2,
      full_title: "Once More Unto The Breach...",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Stormwatch, Vol. 1",
      issue: "3",
      issue_nr: 3,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Strange Adventures, Vol. 3",
      issue: "TP",
      issue_nr: null,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "TP",
      publisher: "DC Comics",
      release_date: "Mar 31, 2010",
      release_year: 2010,
      genre: "Action | Adventure | Science Fiction | Super-Heroes",
      format: "Trade Paperback",
      pages: 256,
      price: 19.99,
    },
    {
      series: "Tribe",
      issue: "1A",
      issue_nr: 1,
      full_title: "Tribe",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 28,
      price: 2.5,
    },
    {
      series: "WildC.A.T.s / X-Men: The Golden Age",
      issue: "1B",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Marvel Comics and Image Comics",
      release_date: "Feb 1997",
      release_year: 1997,
      genre: "Action | Adventure | Historic | Super-Heroes | War",
      format: "Comic",
      pages: 48,
      price: 4.5,
    },
    {
      series: "WildC.A.T.s / X-Men: The Silver Age",
      issue: "1B",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Marvel Comics and Image Comics",
      release_date: "Jun 1997",
      release_year: 1997,
      genre: "",
      format: "Comic",
      pages: 0,
      price: 4.5,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "0A",
      issue_nr: 0,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jun 29, 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 24,
      price: null,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "Resurrection Day",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Aug 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "2B",
      issue_nr: 2,
      full_title: "Revelations",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Image Comics",
      release_date: "Oct 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "3A",
      issue_nr: 3,
      full_title: "Reunification",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Dec 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "4A",
      issue_nr: 4,
      full_title: "Resolution",
      subtitle: "For Whom the Bell Tolls. . .",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Mar 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "6A",
      issue_nr: 6,
      full_title: "Killer Instinct, Chapter One",
      subtitle: "",
      story_arc: "Killer Instinct",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Dec 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "7A",
      issue_nr: 7,
      full_title: "Killer Instinct, Chapter Three: Showdown",
      subtitle: "",
      story_arc: "Killer Instinct",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jan 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "8A",
      issue_nr: 8,
      full_title: "Down Time / Passed Lives",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Feb 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "10",
      issue_nr: 10,
      full_title: "Gateway, Part 1",
      subtitle: "",
      story_arc: "Gateway",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Apr 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "13A",
      issue_nr: 13,
      full_title: "HellC.A.T.S.",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Sep 1994",
      release_year: 1994,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.s, Vol. 1",
      issue: "31A",
      issue_nr: 31,
      full_title: "Cats And Dogs",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Sep 1996",
      release_year: 1996,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.S. Trilogy",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jun 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "WildC.A.T.S. Trilogy",
      issue: "2A",
      issue_nr: 2,
      full_title: "Hell Hath No Fury...",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Sep 1993",
      release_year: 1993,
      genre: "Action | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "WildC.A.T.s: Sourcebook",
      issue: "1",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Sep 1993",
      release_year: 1993,
      genre: "Reference",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Wildcats, Vol. 2",
      issue: "2",
      issue_nr: 2,
      full_title: "Voodoo",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "DC Comics",
      release_date: "May 1999",
      release_year: 1999,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Wildcats, Vol. 2",
      issue: "4",
      issue_nr: 4,
      full_title: "Firefight",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "DC Comics",
      release_date: "Sep 1999",
      release_year: 1999,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Wildcats, Vol. 2",
      issue: "5A",
      issue_nr: 5,
      full_title: "Coda-fied",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "DC Comics",
      release_date: "Nov 1999",
      release_year: 1999,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Wildcats, Vol. 2",
      issue: "6",
      issue_nr: 6,
      full_title: "The Chase",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "DC Comics",
      release_date: "Jan 2000",
      release_year: 2000,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Wildcore",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Nov 1997",
      release_year: 1997,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 3.5,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "71A",
      issue_nr: 71,
      full_title: "Cutting the Mustard",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Aug 20, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "72A",
      issue_nr: 72,
      full_title: "Multiple Homicide",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 17, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "73A",
      issue_nr: 73,
      full_title: "Crowd Control",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Oct 15, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "74A",
      issue_nr: 74,
      full_title: "Politically Incorrect",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Nov 19, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "75A",
      issue_nr: 75,
      full_title: "The Nasty Boys",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Dec 17, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 48,
      price: null,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "76A",
      issue_nr: 76,
      full_title: "X-Communication",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jan 21, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "77A",
      issue_nr: 77,
      full_title: "Great X-Pectations",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 18, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "78A",
      issue_nr: 78,
      full_title: "Playing With Fire!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 17, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "79A",
      issue_nr: 79,
      full_title: "Rhapsody In Blue",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 21, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "80A",
      issue_nr: 80,
      full_title: "Belles Whistles",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "May 19, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Factor, Vol. 1",
      issue: "81A",
      issue_nr: 81,
      full_title: "Belles of the Ball",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jun 16, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "1B",
      issue_nr: 1,
      full_title: "A Force to be Reckoned With",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Marvel Comics",
      release_date: "Aug 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.5,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "1C-1",
      issue_nr: 1,
      full_title: "A Force To Be Reckoned With",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "C-1",
      publisher: "Marvel Comics",
      release_date: "Aug 1991",
      release_year: 1991,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "The Blood Hunters",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jul 30, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "3A",
      issue_nr: 3,
      full_title: "Battle Cry",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Aug 28, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "4A",
      issue_nr: 4,
      full_title: "Sabotage - Part 2",
      subtitle: "",
      story_arc: "",
      crossover: "Sabotage",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 24, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "5A",
      issue_nr: 5,
      full_title: "Under the Magnifying Glass",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Oct 22, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "6A",
      issue_nr: 6,
      full_title: "Under the Gun",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Nov 26, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "7A",
      issue_nr: 7,
      full_title: "Under the Knife",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Dec 30, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "8A",
      issue_nr: 8,
      full_title: "X-Tenuating Circumstances, Part 1: Flashed Before My Eyes",
      subtitle: "",
      story_arc: "X-Tenuating Circumstances",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jan 28, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "9A",
      issue_nr: 9,
      full_title:
        "X-Tenuating Circumstances, Part 2: Underground and Over the Top",
      subtitle: "",
      story_arc: "X-Tenuating Circumstances",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 25, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "10A",
      issue_nr: 10,
      full_title: "X-Tenuating Circumstances, Part 3: Answers (And Questions)",
      subtitle: "",
      story_arc: "X-Tenuating Circumstances",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "May 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Force, Vol. 1",
      issue: "11A",
      issue_nr: 11,
      full_title: "Friendly Reminders",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 28, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "1A",
      issue_nr: 1,
      full_title: "Rubicon",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Aug 20, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "1B",
      issue_nr: 1,
      full_title: "Rubicon",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Marvel Comics",
      release_date: "Aug 20, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "1C",
      issue_nr: 1,
      full_title: "Rubicon",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "C",
      publisher: "Marvel Comics",
      release_date: "Aug 20, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 48,
      price: null,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "1D",
      issue_nr: 1,
      full_title: "Rubicon",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "D",
      publisher: "Marvel Comics",
      release_date: "Aug 20, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "1E",
      issue_nr: 1,
      full_title: "Rubicon",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "E",
      publisher: "Marvel Comics",
      release_date: "Aug 20, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 48,
      price: null,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "Firestorm",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Sep 03, 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "3A",
      issue_nr: 3,
      full_title: "Fallout!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Dec 1991",
      release_year: 1991,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "4A",
      issue_nr: 4,
      full_title: "The Resurrection and the Flesh",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jan 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "5A",
      issue_nr: 5,
      full_title: "Blowback",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Feb 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "6A",
      issue_nr: 6,
      full_title: "Farther Still",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "7A",
      issue_nr: 7,
      full_title: "Inside ... Out!",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "8A",
      issue_nr: 8,
      full_title: "Tooth and Claw",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Mar 17, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "9A",
      issue_nr: 9,
      full_title: "The Not So Big Easy",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Apr 21, 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "10A",
      issue_nr: 10,
      full_title: "Where Happy Little Bluebirds Fly..",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Jul 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men, Vol. 1",
      issue: "11A",
      issue_nr: 11,
      full_title: "The X-Men Vs. The X-Men! (Again)",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Marvel Comics",
      release_date: "Aug 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.25,
    },
    {
      series: "X-Men: Shattershot",
      issue: "HC",
      issue_nr: null,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "HC",
      publisher: "Marvel Comics",
      release_date: "Dec 11, 2019",
      release_year: 2019,
      genre: "Action | Adventure | Super-Heroes",
      format: "Hardcover",
      pages: 616,
      price: 75,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "0A",
      issue_nr: 0,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Dec 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "0B",
      issue_nr: 0,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Image Comics",
      release_date: "Dec 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "1B",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Image Comics",
      release_date: "May 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "1D",
      issue_nr: 1,
      full_title: "Youngblood",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "D",
      publisher: "Marvel Comics",
      release_date: "May 1992",
      release_year: null,
      genre: "Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "2A",
      issue_nr: 2,
      full_title: "Prophecy",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "2B",
      issue_nr: 2,
      full_title: "Prophecy",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Image Comics",
      release_date: "Jul 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "3",
      issue_nr: 3,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Aug 1992",
      release_year: 1992,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 40,
      price: 2.5,
    },
    {
      series: "Youngblood, Vol. 1",
      issue: "4",
      issue_nr: 4,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Feb 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Youngblood: Battlezone",
      issue: "1",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "May 1993",
      release_year: 1993,
      genre: "Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 1.95,
    },
    {
      series: "Youngblood: Strikefile",
      issue: "1A",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Apr 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Youngblood: Strikefile",
      issue: "1B",
      issue_nr: 1,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "B",
      publisher: "Image Comics",
      release_date: "Apr 01, 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: null,
    },
    {
      series: "Youngblood: Strikefile",
      issue: "2A",
      issue_nr: 2,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "A",
      publisher: "Image Comics",
      release_date: "Jul 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
    {
      series: "Youngblood: Strikefile",
      issue: "3",
      issue_nr: 3,
      full_title: "",
      subtitle: "",
      story_arc: "",
      crossover: "",
      variant: "",
      publisher: "Image Comics",
      release_date: "Sep 1993",
      release_year: 1993,
      genre: "Action | Adventure | Super-Heroes",
      format: "Comic",
      pages: 32,
      price: 2.5,
    },
  ];
};
