module.exports = function () {
  return {
    series: [
      "Jim Lee",
      "Rob Liefeld",
      "J. Scott Campbell",
    ],
    items: [
      {
        series: "Jim Lee",
        issue: "60 for 60",
        issue_nr: 1,
        full_title: "",
        subtitle: "",
        release_date: "July 2022",
        release_year: 2022,
        format: "Misc",
        pages: 128,
        price: 3.95,
      },
      {
        series: "Rob Liefeld",
        issue: "Signed Comic",
        issue_nr: 1,
        full_title: "",
        subtitle: "",
        release_date: "July 2022",
        release_year: 2022,
        format: "Misc",
        pages: 128,
        price: 3.95,
      },
      {
        series: "J. Scott Campbell",
        issue: "Sketch Book 1",
        issue_nr: 1,
        full_title: "",
        subtitle: "",
        release_date: "July 2022",
        release_year: 2022,
        format: "Misc",
        pages: 128,
        price: 3.95,
      },
      {
        series: "J. Scott Campbell",
        issue: "Sketch Book 2",
        issue_nr: 2,
        full_title: "",
        subtitle: "",
        release_date: "July 2022",
        release_year: 2022,
        format: "Misc",
        pages: 128,
        price: 3.95,
      },
      {
        series: "J. Scott Campbell",
        issue: "Sketch Book 3",
        issue_nr: 3,
        full_title: "",
        subtitle: "",
        release_date: "July 2022",
        release_year: 2022,
        format: "Misc",
        pages: 128,
        price: 3.95,
      },
      {
        series: "J. Scott Campbell",
        issue: "Sketch Book 4",
        issue_nr: 4,
        full_title: "",
        subtitle: "",
        release_date: "July 2022",
        release_year: 2022,
        format: "Misc",
        pages: 128,
        price: 3.95,
      },
    ],
  };
};
