module.exports = function(){
  return [
    "Angela",
    "The Art of Homage Studios",
    "Cable and The New Mutants",
    "The Creech",
    "The Creech: Out for Blood",
    "Cyberforce, Vol. 1",
    "Cyberrad, Vol. 2",
    "Darker Image",
    "Deathblow, Vol. 1",
    "Divine Right",
    "DV8 vs. BlackOps",
    "Fantastic Four, Vol. 2",
    "Gen 13, Vol. 1 (1994)",
    "Ghost Rider, Vol. 2",
    "Hero Illustrated",
    "Image Plus",
    "Image Zero",
    "Images of Shadowhawk",
    "The Incredible Hulk, Vol. 1",
    "Iron Man, Vol. 2",
    "Jim Henson's Power of The Dark Crystal",
    "Justice League Europe / International",
    "Marvel Swimsuit Special",
    "The Maxx",
    "New Mutants, Vol. 1",
    "Pitt",
    "Savage Dragon vs. Savage Megaton Man",
    "The Savage Dragon [SP]",
    "Savage Dragon, Vol. 1",
    "Shadowhawk, Vol. 1",
    "Shadowhawk, Vol. 2",
    "Spawn",
    "Spider-Man, Vol. 1",
    "Spider-Man vs. Venom",
    "Spider-Man: Torment",
    "Star Wars: Episode 1 - Phantom Menace",
    "Stormwatch, Vol. 1",
    "Strange Adventures, Vol. 3",
    "Tribe",
    "WildC.A.T.s / X-Men: The Golden Age",
    "WildC.A.T.s / X-Men: The Silver Age",
    "WildC.A.T.s, Vol. 1",
    "WildC.A.T.S. Trilogy",
    "WildC.A.T.s: Sourcebook",
    "Wildcats, Vol. 2",
    "Wildcore",
    "Wizard: Magazine",
    "X-Factor, Vol. 1",
    "X-Force, Vol. 1",
    "X-Men, Vol. 1",
    "X-Men: Shattershot",
    "Youngblood, Vol. 1",
    "Youngblood: Battlezone",
    "Youngblood: Strikefile",
  ]
}